%¾ùÔÈ·Ö¸î
figure
subplot(2,2,1)
text(.5,.5,{'1'},...
    'FontSize',20,'HorizontalAlignment','center')
subplot(2,2,2)
text(.5,.5,{'2'},...
    'FontSize',20,'HorizontalAlignment','center')
subplot(2,2,3)
text(.5,.5,{'3'},...
    'FontSize',20,'HorizontalAlignment','center')
subplot(2,2,4)
text(.5,.5,{'4'},...
    'FontSize',20,'HorizontalAlignment','center')
