clear all;
fs=1000;                  
t=0:1/fs:0.6; 
f1=150; 
f2=250; 
x=sin(1.8*pi*f1*t)+sin(1.8*pi*f2*t); 
subplot(411); 
plot(x); 
title('f1(150Hz)、f2(250Hz)的正弦信号'); 
grid on; 
number=512; 
y=fft(x,number); 
n=0:length(y)-1; 
f=fs*n/length(y);   
subplot(412); 
plot(f,abs(y)/max(abs(y))); 
hold on;
plot(f,abs(fftshift(y))/max(abs(y)),'r');
title('f1、f2的正弦信号的FFT'); 
grid on; 
x=x+randn(1,length(x)); 
subplot(413); 
plot(x); 
title('原始信号'); 
grid on;
y=fft(x,number); 
n=0:length(y)-1; 
f=fs*n/length(y);
subplot(414); 
plot(f,abs(y)/max(abs(y))); 
title('原始信号的FFT'); 
grid on;
