clear all;
file_name = 'circuit.tif';
I = imread(file_name);
normal_edges = edge(I,'canny');
subplot(2,3,1);imshow(I);
title('Ô­Ê¼Í¼Ïñ');
subplot(2,3,2);imshow(normal_edges);
title('±ßÔµ¼ì²â´¦Àí');
block_size = [50 50];
edgeFun = @(block_struct) edge(block_struct.data,'canny');
block_edges = blockproc(file_name,block_size,edgeFun);
subplot(2,3,3);imshow(block_edges);
title('·ÖÀëÁÚÓò²Ù×÷');
border_size = [10 10];
block_edges = blockproc(file_name,block_size,edgeFun,'BorderSize',border_size);
subplot(2,3,4);imshow(block_edges);
title('ÁÚÓò±ß¿ò');
thresh = 0.09;
edgeFun = @(block_struct) edge(block_struct.data,'canny',thresh);
block_edges = blockproc(file_name,block_size,edgeFun,'BorderSize',border_size);
subplot(2,3,5);imshow(block_edges);
title('ãĞÖµ');
