hf=figure('Position',[200 200 600 400] ,...
           'Name','Uicontrol1' ,...
           'NumberTitle','off');
ha=axes('Position',[0.4 0.1 0.5 0.7],...
            'Box','on',...
          'XGrid','on',...                                      %x有网格
         'YGrid','on');                                          %y有网格
 htg=uicontrol(gcf,'style','toggle',...                  %切换按钮  
      'string','Grid on',...
      'position',[50,200,100,40],...
      'callback',[...
                 'grid;'...
      'if length(get(htg,''String''))==7 & get(htg,''String'')==''Grid on'';'...
                 'set(htg,''String'',''无网格'');'...  %改变字符显示
                 'else;'...
                'set(htg,''String'',''有网格'');end;'...%改变字符显示
                 ]);
