clear
clc
hf=figure('Position',[200 200 600 400] ,...
           'Name','Uicontrol1' ,...
           'NumberTitle','off');
ha=axes('Position',[0.4 0.1 0.5 0.7],...
            'Box','on');
hlist=uicontrol(gcf,'Style','list',...                   %列表框
                 'position', [50,140,100,100],...
    'string','.     point|-     solid|o     circle|:     dotted|x     x-mark|-.    dashdot|--    dashed|+     plus|s     square|d     diamond|*     star',...
                 'Max',2);                           %调用PlotSin
