hf=figure('Position',[200 200 600 400] ,...
           'Name','Uicontrol1' ,...
           'NumberTitle','off');
htDemo=uicontrol(hf,'Style','text',...           %文本标签
                  'Position',[100 100 100 30],...
                  'String','静态文本示例');
