clear
clc
hf=figure('Position',[200 200 600 400] ,...
           'Name','Uicontrol1' ,...
           'NumberTitle','off');
ha=axes('Position',[0.4 0.1 0.5 0.7],...
            'Box','on');
hcGrid=uicontrol(hf,'Style','check',...                 %复选框
               'Position',[50 240 100 20],...              %复选框位置
               'String','Grid on',...
               'Value',1,...
               'CallBack',[...
                             'if get(hcGrid,''Value'')==1;' ... %判断是否选中
                              'Grid on;'...
                              'else;'...
                             'Grid off;'...
                              'end;'...
                               ]);   
